[General]
Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xe7\0\0\x2\x89\0\0\0\0\0\0\0\0\0\0\x4\xe7\0\0\x2\x89\0\0\0\0\x2\0\0\0\x5\0\0\0\0\0\0\0\0\0\0\0\x4\xe7\0\0\x2\x89)
Zoom=5

[Current]
Algorithm=4
Player=@Point(22 22)
Progress="@ByteArray(\0\0\x13\x88x\xda\x9dX\x81v\xdc\x30\bC\xc0\xff\x7f\xf3\x36\xc7\b\xd9\xdd\x16;\xe9k\xef.\x8d\x8d\x1I\xc0\x99\xf9\xef\x9f\x34\xc8o\x8e\xd7\xe7\xc2x\xf7\xdc\xad'\xff\xbc\x62\xbc\xcf\xf1\xbf\xb7\xcb-\xe6\x1e\x31~\x9f\x1d\x62\xec\xf2\xec\x1e\x63_\x8c\xe7\x62<\xe9\xe3\xd5\xc6\xe7g]\xfe\xd7\x46\xf0\x84\xe0\x1a\xe3N&w\xeb>\xc6\t|\xae\x89y\xa6\xb7+\x18\x8b\xa4\xd5`\xe4|~\xae\xd3\xc4\xf4,\xa7\xf7\xf1\xe2\x85\xcd\x98\xf4\xa9\xca\xab\x18\xf7S\xee;\xa3\xe8\x8b\xc5w/b>\xf7\x9c\xca\x64}\xd0V\xce\x88\xed\xd1=\xb3P+\xeb\xcc\xe5Ie\x12\x33\xdf\xf5\x1f=\x99\x1f\x66\xe2\xb1\xe1\x12\x9f\x8e\a\xc6\xe7`\xa4\xda\xca\xe3+^\xf3`\xc4\x7f\xa1\xbf\x10\\\xbb\x63\xe2\xa9>'1\x1d\xd3\x46\x1c\xdbH\xe2\x13\xf3\x84\xf5\xb7\xd9\xf6\x30\xae\x18\x12\x64\x93\x1dyS\x91\xe8UAFBvj\xc6\x61\xf2\xbdQn\a\xd8\xf5\xe9\xb7\x33+\x85\x1d\bw\x9cy\b\xae\xdd\xb1\xf0/?\x9c\xf8\xad\xfd\xd4j0R+\xd6\xc1\xe7\xed\xd5\x93\xd6\xc0\xd6\xa5\x14\xd6$\xf5#\x17\xe\x16.\xec\xc8\x46\x45\xa4\xe3mdI\xd2\x8a\t7\x8b\xab\xa7j\x5>\xab\xdc(\x8d\xd4\x38\x35\xfb;\x1fy\x84_\xcdq,\x15\x1\x62\x11\x92\xf3SV\xecv\xfa\xec\x8d\xdb\x94\x88\xa9\xb5\x38\xe6\xb7\x62\xd7\xa8\x89\x39Y\f\xa9)F\xae\xdc\xc4g\xd7\xdd\x46!6u\xf2\x45\xb9\xba\x96\xdc\xdaP\x7f:/N\xf4\x1a\xd5\x32\xa4:\xdf\xd9\xe8n\xc1\x96\x98\x83\xbe\x35\x7fZ\x17\xefl\xa4\x44\x42\x31\fAZ3;>XQ\x84\xc6\x82\x1f\xcc\xba\x2\xaaV\xb0~\xe3\n[`\xa5m\x5l\xfe\x1b\x95^5r\xe5\xe9\x19\xae\x42\xf8\x9e\xac$X\xf2\xac\x8a\xdc\xbd\xde\x99\x1dgE\xf\xd1\xf9\xd6\xc7\xb5jk_g\xf3/\x8e\xfcH\xa2\xbe;\x8dX\xfc\xe8\xdc\xad\xbb\x86t\xad\xff\xc7\x95\xf6\xb4\x90\xbe\x44+6\x16\x34\xaf\xeb\xdfmtu*\xae\x41\x14K\x9f\x3YrwAr\\g\a\xcf\xd7\xa7\x4k\xcb\xfdU\xcc\xb2\xadJ\xedZ\xf3\xcd\x83umJ\xe7\a*l\x8aZ~\xbf\\\xe2\x94K=j\x14\x9f\xa1\xe7]K\xb0u\xcb.\x93\x6>g\xa2m\xb8hS\b\x8b\x31\x33\xa5*\xf6=\x1fX:\x9a\xa0\xd6\xc6\x8f\xe\xe5\xcb\x15\xb2wOz\xa5\x1f.^\xda\x87J\xaez\xe5\xec\x31\xab\x97\xaa\x1c\x80\x95\xa9\x14\xc0\xe;\xe9\xbd\xe\x9apX'IH\xad\xedJ\x8e\xcb\x9a\x1e\xd2}\xbat\xbf\xaa\xdd\xc1J\x1c\x32o\xdd\xd5Z\x93\xeemgd\xb2RA\xe6\x85\xbc\x62}\xf7\x9c\xf1\xe3\xe4\xb9M\x89]\x81\xedx\x16\x34\x99\xf6\xbbGl\x8bZ\x15\v\t\x8d\x91\xbb>\xb4\x10\x84\xadr\xfb\xf2z;\xcd\xfe}\n\x81\xe0\x38\x39\xf3\xbah\xc0\x37\xe5\xad\xea\xd9]fPat\xcaI\xce\xa4_m\xac\xdf\xc9\xac\x93`\xb2\xcf\xcd\x8fsA\x88\x2:;6\x93\xba\xeb\x8b\xd6\xdbg+\xeb\x37$\xb1L\x1d\xdd\xb9\xf8G\x1b\xbf\0\x18\xc6\f\xaf)"
Rotation=360
Seed=4087375163
Size=50
Steps=3145
Targets=3
Time=960182
Version=3

[New]
Algorithm=4
Size=50
Targets=3

[Scores]
DefaultName=SaboTabby

[Scores_Cutemaze]
1\Algorithm=4
1\Name=SaboTabby
1\Seconds=1032
1\Size=50
1\Steps=338
2\Algorithm=4
2\Name=SaboTabby
2\Seconds=488
2\Size=20
2\Steps=181
size=2
