[General]
Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x2l\0\0\x2\x8d\0\0\0\0\0\0\0\0\0\0\x2l\0\0\x2\x8d\0\0\0\0\x2\0\0\0\x5\0\0\0\0\0\0\0\0\0\0\0\x2l\0\0\x2\x8d)
Zoom=5

[Current]
Algorithm=4
Player=@Point(14 30)
Progress="@ByteArray(\0\0\x13\x88x\xda\xa5X\x89v\xc3 \f\xf3\xf5\xff\xdf\xbc\x8d`YfG\x80\xa5\xafM\x93\x6\x8c\x8d,\xd9\x15\xb1\xcfW\x88\xd2;\xc6\xf9\x39t|{\xee\xe6\x93_g\x1d\xdf\x63\xfc\xf6v\x98\xf8\x9c\xc3\xc7\xfb\x99\xc1\xc7,\xcf\xec>\xe6\xd5\xf1\x9c\x8f'm\x9c\x65\\?\xe3\xe2O\x1b\x8e\x15*\xc6\bf\x12\xba\x9b\xf7u\xac\xc0\xe6\x18\x9fkz;\x1c\xb1\bXuD\xce\xe6u\xae\xc6\xa7g1\xbd\xf7\x17/d\xc6\xa4V\x95^\xf9\xb8\x1ft\xdf\x10\x45k\x16\xdf\xbd\xf0\xf9\xdc\xb3*\xa1\xf1\xe[1#\xb6\x46w\xcf\x42\x8e\xcc\x35\xa7'\xb9\x93:\xf7;\x7f\xe1\x95\xd9\xe6N<6\x8c\xe2S\xf1\xd0q\xed\x88TYy|\xd5\xd7}\x10\xe0?\xd1\x9f\b\xce\xd9u\xe2)\xaf\x3\x98\xf6i\xc3\xb7m\x4\xf0\xa9s\x85\xf9Y\xd9\xf6\x64\\f\x88#\x9b\x64\xcb\x9b\x8c\x44\x8drd\xa4\xd2L\x95q:\xf3\xbdP.\x1b\xd8\xb5\xe9\xb7\x61W\x12;J\xb9\x63\xd8\a\xc7\xd8\x15\v\xbf\xf9\x61\xc0o\xce\xc7V\x1d\x91\xeaXW</\xaf\x9e\x14\a\x16/\x5\x65M\x80?\xa2\xe5`\xe1\x62\xc7\x46\x46\xa4\xe2-\xc8\x92\x80\x15\xa1\xdc\xcc\\\xdd\x65+\xc5\xb3\x9c\x1b\xc9\x91\x1c\xa7\xca\xfe\xda\x8f\xd8\xc2/\xef\xb1\x37\x45P\xb2\xa8\xb4\xe7\xbbY\xb1\xda\xa9\xb5\x17n\x83\"\xc6\xd6|;\xbf\x19\xbb\x2N\x8c\x99\xc5J\x9a\"\xc8\x95\x93\xf8\xac\xbc[(\xd4\x85\x9d\xac\x31Wi\xc9\xa9\r\xf6\xa7\xf6\xc5\x80^\x1[:\xa9\xf3\x99\x8d\xaa\x16\xa4\xc5\\\xe1[\xe5O\xf1\xe2\x99\x8d\xa0H0\x86\x95\x90V\x99\xed\x17V\x18\xa1\xde\xf0\xa3SW\x14\xac\xe5\xd0o=\xc2\x96\x42i\x8b\x1+\xff\x5L\xcf\x1c\xd9\xf3t\xfWN\xf9\x1eP\x12m\xfb\xcc\x8c\\\xb5\xde\x9e\x1d\x83\xa2;\xf1|\xf1#W#\xd1\xea:\x81\xe6\xef\xf8\x11@}U\x1a\xe?\x14\xbc\x97\xdc\xa5\r1\xba\x85+\xaei\x95\xea\x12m\x9a\xc8h\xee\xe3\xdfm\x94:\xe5\xaa\x95\x18\xcbZ\x95\xa0\x1b\xd5\xedoz\xce\x33\x97\x82\b\xb4\"\xb9R\xaf\x38\x37\x33K\x16\x95\xea\xf5\xd7\xad\a\xecGU\x5U\xf7\x1b\xd5\xd6\xb7\x1e\xacuI\xe1\x9d+\xff\xca\x98\xfb\x43\x89\x7f\xbc\xf9S\x9d\x86\xfe\xd3\xf\xee\xbc\x8aMX\xaf\xac\xb1\xd8\xfd~h\xabh\x1c\\\xeb\xdf*\x94\x9b\xc3i\xee\xea\xf4\x32\xb3\x8d\xbc\x94\v%g\xbe\x32\xd4\x98YK\xe5\x1e(\x94)\x19@6+\xe9U\a\x85\x32\x80;I%\xad-%\xd7\x43Mw\xaa>\x8d\xaa_\xe6n\x87\x12;\xf5[gZ+T\xbd\xad\x19\x19P*\xa5~!\x8e\xb2\xbejN\xff\xb6\xf2X\xba\xc4R`\xd9\xee\x5\x85\xba\xfd\xe2\xbd\xb2\xc8\xaa\x98H(\x8c\x9c\xd5\xa1\x89 ]\x94\xdb\xda\xf9\xb4\x9b\xfd\xb9\vQ\xc2q\x80s\x8d\x38\xe0\x8eyS=\xab\xcat0\fw9\x81\x9e\xf4\xd6\x46\xffO\xa6w\x82\x81:7.\xfb\x2'\x6\x34\xa8\x91\x90\xeeZ\xe3z\xb9\xb6\xd2\xff!\xf1\xd6uT\xe5\x62\x97\x36>\0\xeb;\f\xe5)"
Rotation=180
Seed=4087375163
Size=50
Steps=3377
Targets=3
Time=1031033
Version=3

[New]
Algorithm=4
Size=50
Targets=3

[Scores_Cutemaze]
1\Algorithm=4
1\Name=SaboTabby
1\Seconds=1032
1\Size=50
1\Steps=338
2\Algorithm=4
2\Name=SaboTabby
2\Seconds=488
2\Size=20
2\Steps=181
size=2
